update_documentation: commit changes to sxl traffic lights

diff --git a/.github/workflows/update_documentation.yml b/.github/workflows/update_documentation.yml
--- a/.github/workflows/update_documentation.yml
+++ b/.github/workflows/update_documentation.yml
@@ -44,10 +44,29 @@ jobs:
   build-sxl-tlc:
     runs-on: [ self-hosted, Linux ]
     steps:
+    - name: Check out rsmp_documentation repository
+      uses: actions/checkout@v2
     - name: Check out rsmp_sxl_traffic_lights repository
       uses: actions/checkout@v2
       with:
         repository: rsmp-nordic/rsmp_sxl_traffic_lights
         ref: ${{ github.event.client_payload.ref }}
-    - name: Build rsmp_core repository
-      run: make html
+    - name: Build rsmp_sxl_traffic_lights repository
+      run: |
+        cd rsmp_sxl_traffic_lights
+        make html
+    - name: Commit documentation changes
+      run: |
+        mkdir -p docs/rsmp_sxl_traffic_lights
+        cp -r rsmp_sxl_traffic_lights/build/html/* docs/rsmp_sxl_traffic_lights
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add docs/rsmp_sxl_traffic_lights
+        git commit -m "Update documentation" -a || true
+        # The above will fail if no changes were present, so
+        # we ignore the return code.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: main
+        github_token: ${{ secrets.GITHUB_TOKEN }}
